### ISSUE TITLE
Have nticks be respected when tickmode='array'

### ISSUE THREAD

**Issue by talgalili** [plotly/plotly.js#1812]
Examples for how it should work (using R's plotly package)

Works fine:
```r
library(plotly)
p <- plot_ly(
    width = 800,
    height = 500
  ) %>% layout(
    title = "fixed-ratio axes",
    xaxis = list(
      nticks = 10,
      domain = c(0, 0.45)
    ) )
p
```

![image](https://user-images.githubusercontent.com/976006/27492110-aa32bf48-584d-11e7-93c5-ff29ae687527.png)

Does not yet work:

```r

library(plotly)
p <- plot_ly(
    width = 800,
    height = 500
  ) %>% layout(
    title = "fixed-ratio axes",
    xaxis = list(
      nticks = 10,
      domain = c(0, 0.45),
	tickmode='array'
    ) )
p
```

![image](https://user-images.githubusercontent.com/976006/27492104-a3f384dc-584d-11e7-8558-1be0bff98954.png)

This feature is specifically important for creating cluster-heatmaps that allow more refined control over the number of ticks (see [here](https://github.com/talgalili/heatmaply/issues/78))

**Comment by etpinard** [comment]
That's the [intended](https://github.com/plotly/plotly.js/blob/master/src/plots/cartesian/tick_value_defaults.js) behavior. Setting `tickmode: 'array'` turns off the auto-ticks (where `nticks` is used).

When you say

> Does not yet work:

What do you mean? What is the expected behavior in your mind?

**Comment by Alanocallaghan** [comment]
I think the desired output in this instance is for the user to be able to manually specify tick values and labels, but also apply the "auto" tick generating method.

For example, here I am creating a heatmap with categorical labels and automatic ticks by specifying the x co-ordinates, and tick generation works nicely:
https://codepen.io/alanoc/pen/yXPgEp

However, in some cases it is desirable to map categorical scales to numerical scales, in order to present them side-by-side with other plots (and, more importantly, aligned), while maintaining meaningful categorical ticks. For example, heatmaps are commonly presented with dendrograms aligned to rows and columns, in order to show relationships between samples (eg, https://i.stack.imgur.com/1qTWn.png).
To accomplish this, I would commonly specify a numeric axis and tick values, but character tick text. In this case, label overplotting is very common:
https://codepen.io/alanoc/pen/WOXRLE

Perhaps `tickvals` and `ticktext` are not the right parameters to be used in this instance, as they do imply the values actually used for ticks; however I do think it would be useful to have this level of control.

**Comment by JuankS92** [comment]
This is a problem we are facing right now. I want to be able to [add ellipsis to the labels in the X axis](https://community.plot.ly/t/ellipsis-for-truncated-axis-labels/4752), so we use ticktext and tickvals to set the values on the labels. As you can see in the example above by @Alanocallaghan the number of ticks might be a huge amount of data so in those cases, the auto setting is disabled and the labels become unreadable. Perhaps we should be able to handle the number of ticks shown on the graph or let the auto handling for the number of ticks to be available instead of making them [mutually exclusive](https://community.plot.ly/t/defining-nticks-when-using-ticktext-tickvals/659).

**Comment by etpinard** [comment]
Merging with https://github.com/plotly/plotly.js/issues/1812

**Comment by Alanocallaghan** [comment]
@etpinard this issue is #1812

**Comment by alexcjohnson** [comment]
As discussed in https://github.com/plotly/plotly.js/pull/1965#issuecomment-335346105 I think this is a different issue, and might be solved by something like #303 which we could generalize for the `tickmode = 'array'` case like "iterate through the array and display each tick iff it's more than n pixels away from all the others we've already drawn"

**Comment by Alanocallaghan** [comment]
I think that's right @alexcjohnson, thanks for the clarification

**Comment by talgalili** [comment]
Thanks @alexcjohnson for the clarification and for re-opening this.
I'm looking forward for #303 to be resolved, so that you or others could try to leverage it to solve this issue.

**Comment by talgalili** [comment]
Hello @etpinard  (and @alexcjohnson),
I see that you wrote in #1946 that it would provide a solution to this issue. I see it is now closed thanks to #1965. Does this mean that this issue is now also resolved? If not, what else should be done in order to address it?

Thanks.

**Comment by alexcjohnson** [comment]
@talgalili this is separate from #1946 and #1965, as mentioned in https://github.com/plotly/plotly.js/issues/1812#issuecomment-335348104

We need to resurrect #303 and incorporate this into it. Unfortunately Plotly folks are extremely busy for the next few months so I don't see this getting addressed in the near future without a community volunteer to spearhead it.

**Comment by talgalili** [comment]
Thanks @alexcjohnson - I've added a comment on #303 and I hope someone could take it upon themselves to add this.

**Comment by jackparmer** [comment]
This issue has been tagged with `NEEDS SPON$OR`

A [community PR](https://github.com/plotly/plotly.js/pulls?q=is%3Apr+is%3Aopen+label%3A%22type%3A+community%22) for this feature would certainly be welcome, but our experience is deeper features like this are difficult to complete without the Plotly maintainers leading the effort.

**Sponsorship range: $5k-$10k**

What Sponsorship includes:
- Completion of this feature to the Sponsor's satisfaction, in a manner coherent with the rest of the Plotly.js library and API
- Tests for this feature
- Long-term support (continued support of this feature in the latest version of Plotly.js)
- Documentation at [plotly.com/javascript](https://plotly.com/javascript/)
- Possibility of integrating this feature with Plotly Graphing Libraries (Python, R, F#, Julia, MATLAB, etc)
- Possibility of integrating this feature with Dash
- Feature announcement on [community.plotly.com](https://community.plotly.com/tag/announcements) with shout out to Sponsor (or can remain anonymous)
- Gratification of advancing the world's most downloaded, interactive scientific graphing libraries (>50M downloads across supported languages)

Please include the link to this issue when [contacting us](https://plotly.com/get-pricing/) to discuss.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson

**Comment by talgalili** [comment]
Hi @gvwilson 
This problem still hinders/impacts heatmaply.
But given that this wasn't addressed in 7 years now, I don't see a point in asking for it again.
Users would just have to live with the reduced performance due to this issue not getting addressed.

Thanks for your other work.

Tal.
