### ISSUE TITLE
WebGL visualisations not rendering on iOS

### ISSUE THREAD

**Issue by mattpolicastro** [plotly/plotly.js#280]
I've tried opening a few WebGL-powered visualisations (e.g. [wavenumbers](https://plot.ly/~chriddyp/1780.embed)) on iOS devices in Safari but am greeted with "Webgl is not supported by your browser - visit http://get.webgl.org for more info". However, WebGL is [well-supported in Safari](http://caniuse.com/#search=webgl) and is able to render graphics from other libraries (e.g. [three.js](http://threejs.org/)). 

I'm not terribly familiar with the project, but I'm poking around how GL context is determined and when  `showNoWebGlMsg()` is fired in /src/plots/gl3d/scene.js. Am I barking up the right tree, or totally off-base?

**Comment by mikolalysenko** [comment]
It might be that we are passing incompatible parameters to the webgl context creation.  This is hard to test without access to an iOS device.  I'll see if I can scrounge one up or borrow something to test.

**Comment by mattpolicastro** [comment]
This is the error I'm able to trigger from Safari's developer console (iPhone 6 Plus, iOS 9.2.1):
````
TypeError: undefined is not an object (evaluating 'scene.glplot.canvas')              1295
draven.min.js:1:12125
contextraven.min.js:1:11951
(anonymous function)80b358f249c0.js:16382:547
ljquery.min.js:1:17001
fireWithjquery.min.js:1:17784
readyjquery.min.js:1:12515
Ajquery.min.js:1:9914
````
Though raven.js is for Sentry, no?

**Comment by eugenesvk** [comment]
I have the same issue in both Chrome and Safari on iPhone 6 iOS 9.3. Funny thing is visiting  http://get.webgl.org in the error message shows a spinning cube just fine.
Hope you can figure it out and fix so iOS users can enjoy awesome plot.ly 3D charts :)

**Comment by McCulloughRT** [comment]
Has there been any progress on this issue? I'd love to have a working 3D scatter plot on iOS but currently get the same message as above.

**Comment by minimaxir** [comment]
I second the request for progress on this issue. This issue is a blocker for me using 3D charts.

**Comment by smvv** [comment]
Same issue for Firefox running on Android (Samsung Galaxy S6)

**Comment by dfcreative** [comment]
Ok, part of the issue, at least for scatter3d, appears to be in _gl-fbo_ ↑

**Comment by dfcreative** [comment]
[Seems that](http://stackoverflow.com/a/28949220/1052640) iOS just does not allow rendering to floating point textures. It should be fixed [here](https://github.com/gl-vis/gl-plot3d/blob/master/scene.js#L98).

**Comment by climbercarmich** [comment]
It also is a big drawback for me as I use an Ipad often for data visualisation presentations. Any updates on this?

**Comment by dfcreative** [comment]
[This](https://github.com/gl-vis/gl-plot3d/issues/6) should fix 3d-related issues.

**Comment by bg23** [comment]
Surface Plot under iOS 10 still prints "Webgl is not supported by your browser" using plotly.js version 1.24.0.

**Comment by etpinard** [comment]
@bg23 can you share an example?

**Comment by alubbock** [comment]
I'm also getting this error, e.g. on the plotly example 3d surface plots: https://plot.ly/python/3d-surface-plots/

Screenshot below from an iPad Mini 4 running iOS 10.2.1, taken just now.

![screenshot](http://i.imgur.com/hFq5EYg.png)

**Comment by dfcreative** [comment]
@etpinard I fixed that only for mesh3d, so complaints are valid. Can look at other cases.

**Comment by etpinard** [comment]
@dfcreative getting [gl-surface3d](https://github.com/gl-vis/gl-surface3d) to work on iOS would be amazing !!

**Comment by bg23** [comment]
The javascript example at "https://plot.ly/javascript/3d-surface-plots/"
is working under Windows/Chrome and Android/Chrome (the latter OS without touch operations).
Under iOS/Safari however "WebGL is not supported" is displayed.

**Comment by man-bear-pig** [comment]
I still experience this bug in both iOS Chrome (58.0.3029.83) and Safari on 13" iPad Pro.

**Comment by ischurov** [comment]
I wonder why this bug is closed? I definitely see the same error messages in Safari under iOS (i.e. [here](http://math-info.hse.ru/odebook/chapter/label/chap:7:cons/)).

**Comment by etpinard** [comment]
@ischurov @man-bear-pig https://github.com/plotly/plotly.js/pull/1411 (released in `1.24.0`) did fix the problem for _some_ iOS distro, but looks like not _all_. I'll gladly reopen this issue. 

Looking at the reports in detail, the problems appear to only concern `surface` traces. Could anyone here be interested in testing our other WebGL trace types to help us narrow down the problem? For example,

- https://plot.ly/javascript/3d-scatter-plots/
- https://plot.ly/javascript/3d-mesh/
- https://plot.ly/~chris/17389.embed

**Comment by rreusser** [comment]
These all work for me on iPhone 5 except for 3d-mesh, which has lots of black spots @etpinard reports are fixed by #1868. The other exception is @chriddyp's plot which has question mark glyphs for all of the characters.

**Comment by etpinard** [comment]
> The other exception is @chriddyp's plot which has question mark glyphs for all of the characters.

Another argument for :hocho: the current unicode to texture algo cc @dfcreative

**Comment by rreusser** [comment]
Even in the iOS simulator using iOS 10.3 + iPhone 5, it shows ? on the first load and proper glyphs on the second. Is it conceivably possible that it's a font loading issue? Maybe solvable by [this sort of thing](https://www.npmjs.com/package/webfontloader#events)? Not sure why question marks would be the fallback though.

**Comment by bg23** [comment]
On iPad with iOS and Safari 10.3: Scatter and Mesh fail with Webgl not supported.
Hue value is OK, but characters are shown as question marks.



Von meinem iPad gesendet

**Comment by etpinard** [comment]
@bg23 can you go to http://webglreport.com/ to see if your iPad's browser does support WebGL?

**Comment by bg23** [comment]
It supports Webgl 1, but not Webgl 2. All Webgl apps I tried were working,except for plotly.js surface plot.

Von meinem iPad gesendet

**Comment by bg23** [comment]
Fixed for myself locally, see my comment to #1411.

**Comment by bg23** [comment]
The reason for this bug on iPad is the incomplete iPad detection for mobiles:
In "function isMobile (ua)", the check "ip(hone|od)" must be replaced by "ip(ad|hone|od).
Then surface plots will also work on iPads.

**Comment by gittar** [comment]
May 2018 and still plotly seems to believe that ipad cannot do WebGL. Please 
fix if possible. It is for your own good: Mobile devices are key!

**Comment by ShaneHudson** [comment]
I've also got an issue with surface plots not working on ipad.

**Comment by nicolaskruchten** [comment]
It would be helpful if people reporting issues could report the specific *device* and *trace type* where the issues are observed.

From what I can tell, the subject of this issue (i.e. "iOS") is far too broad. As of today, my testing shows that:

* on an iPhone 7 (model number A1778): all trace types work
* on an iPad Air 2 (model number A1566): all trace types work except `scatter3d`, `mesh3d`, `surface`, `cone`, and `streamtube`

Are there any instances of iPhones where certain trace types do not work, or iPads where trace types other than the ones listed above do not work?

**Comment by ShaneHudson** [comment]
For me the issue is surface (and heatmapgl iirc) on iPad 2018
