### ISSUE TITLE
3D plots not showing on Safari Version 14.0 when there is transparency in the scene

### ISSUE THREAD

**Issue by alimm1995** [plotly/plotly.js#5158]
After updating Safari to version 14.0, you can visit https://plotly.com/javascript/3d-mesh/ and observe the empty 3D scatter plots as follows: 
![image](https://user-images.githubusercontent.com/44326170/93705779-01005b00-fad5-11ea-8d3e-4a8977e0d5de.png)

**Comment by archmoj** [comment]
Thanks for the report. Which OS & device you are using?

**Comment by alimm1995** [comment]
Thank you. I am using macOS Catalina 10.15.6 on MacBook Air Retina, 13-inch, 2018. The Safari is Version 14.0 (15610.1.28.1.9, 15610). I want to mention that hover text works on the vertices as follows although the mesh is invisible.
<img width="317" alt="image" src="https://user-images.githubusercontent.com/44326170/93733192-4716f680-fb89-11ea-85bb-d0c3ffe14bf1.png">
On this same device, the 3D meshes can be seen fine one Google Chrome.

**Comment by archmoj** [comment]
Hmm... `browserstack` is still on v13 not v14.
So at the moment it is not possible to debug it there.
@alimm1995 could you also try other 3d traces e.g. `surface` and `scatter3d` with your device?

**Comment by alimm1995** [comment]
The surface plots on   are good. The scatter3d on https://plotly.com/javascript/3d-scatter-plots/ doesn't show.
Sorry for mentioning this detail now, but I just realized that while the first two 3D meshes on https://plotly.com/javascript/3d-mesh/ don't work, the last two meshes on this page work. So I _can_ see the plots under "3D Mesh Tetrahedron" and "3D Mesh Cube."

**Comment by archmoj** [comment]
And I expect you get some warnings in the console e.g.
```
'webgl setup failed possibly due to disabling/enabling preserveDrawingBuffer config.'
```
If that is the case I think this should be addressed in [is-mobile](https://www.npmjs.com/package/is-mobile) module to support Safari v14.

**Comment by alimm1995** [comment]
No, interestingly I don't get any errors regarding that. I only get the following message: 
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/44326170/93798556-baa11e00-fbf2-11ea-880b-4e6043ca5fae.png">
But this error shows in all Plotly.com webpages.

**Comment by smeingast** [comment]
Jumping in here because I just encountered the same issue. I managed to "fix" it by setting the opacity of the lines to 1.0. If I set the opacity to anything below 1 (e.g. 0.99), the lines won't show in Safari 14.0

**Comment by alexcjohnson** [comment]
@archmoj FYI I also see this bug in Safari 14, on Mac OS 11.0.1 Big Sur. No messages show up in the console.

**Comment by andrew-saydjari** [comment]
This problem persists for me in Safari 14.0.1 (16610.2.11.51.8) and MacOS 11.0.1 BigSur. It also interferes with PollEverywhere rendering the html in powerpoint presentations.

**Comment by sthair** [comment]
PS. Reproducible example (given the user has Safari 14.1.1)... 

as per: 
#https://plotly.com/r/3d-line-plots/
## BASIC LINE PLOT
data1 <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/3d-line1.csv')
head(data1)

data1$color <- as.factor(data1$color)
table(data1$color)

plot_ly(data1, x = ~x, y = ~y, z = ~z, 
        type = 'scatter3d', 
        mode = 'lines',
        opacity = 1, 
        line = list(width = 6, color = ~color, reverscale = FALSE)) #WORKS IN SAFARI 14

plot_ly(data1, x = ~x, y = ~y, z = ~z, 
        type = 'scatter3d', 
        mode = 'lines',
        opacity = 0.6, 
        line = list(width = 6, color = ~color, reverscale = FALSE)) #DOES NOT WORK IN SAFARI 14

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/45246061/138009820-b93bdd91-e24c-4ab4-9ed3-3299fffebade.png">
